### ISSUE TITLE
Add optional flags for host and username (and password?)

### ISSUE THREAD

**Issue by mark-keaton** [mwotton/squealgen#10]
I was able to edit the generated `squealgen` script to add the flags I needed (`-h` and `-U`), but it would be nice to be able to pass those flags in instead of editing the Bash script. 

Thanks.

**Comment by mwotton** [comment]
you can actually include both host and username in the database URL you pass to squealgen. Perhaps i should add something to the README to illustrate it.

**Comment by mwotton** [comment]
btw, @mark-keaton , you're the first person I don't know who I know to be using squealgen. First, thanks! Second, there are some interface changes coming up forced by the necessity for cross-schema codegen to work, so the arguments to squealgen are probably about to change.

**Comment by mark-keaton** [comment]
> btw, @mark-keaton , you're the first person I don't know who I know to be using squealgen. First, thanks! Second, there are some interface changes coming up forced by the necessity for cross-schema codegen to work, so the arguments to squealgen are probably about to change.

Thank you for the tool. I heard about it through a Haskell friend of mine, https://github.com/scott-fleischman. Maybe you know him? He actually knows what he's doing, unlike me.

**Comment by mwotton** [comment]
@mark-keaton as it happens I work with him :)
