### ISSUE TITLE
Duplicate keys in hs definitions when foreign key columns match in both tables

### ISSUE THREAD

**Issue by adamwespiser** [mwotton/squealgen#13]
Given the following schema,
```
drop table if exists table_one cascade;
create table if not exists table_one (
   table_two_id INT,
   col_one INT,
   col_two INT);

drop table if exists table_two cascade;
create table if not exists table_two (
   table_two_id INT,
   col_one INT,
   col_two INT);

alter table table_one
  add constraint "table_one_pkey"
  primary key (col_one, col_two);

alter table table_two
  ADD CONSTRAINT "table_two_fkey"
  foreign key (col_one, col_two) references table_one (col_one, col_two);
```

The generated squal types would look like this:
```
type Table_TwoConstraints =
  '[ "table_two_fkey" ::: 'ForeignKey '["col_one", "col_one", "col_two", "col_two"] "public" "table_one" '["col_one", "col_one", "col_two", "col_two"]
   ]
```
With duplicated columns in the foreign key entry for `table_two`.

I've traced this problem back to the `constraintDefs` table, [(defined here)](https://github.com/mwotton/squealgen/blob/master/squealgen.sql#L173), but my attempts to resolve this issue were unsuccessful.

**Comment by mwotton** [comment]
@adamwespiser thanks for the report, this should be fixed in https://github.com/mwotton/squealgen/commit/f9730d3bd8503336df101188d76eedeaa0944659

**Comment by echatav** [comment]
This may need to be re-opened, see above generated invalid foreign key constraint ^
